apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: jzufpzb93-go 
  janus-idp.io/tekton: jzufpzb93-go
  backstage.io/kubernetes-id: jzufpzb93-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: jzufpzb93-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml