apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: jzufpzb93-go-gitops
  description: This is GitOps manifest for jzufpzb93-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=jzufpzb93-go
    backstage.io/kubernetes-id: jzufpzb93-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: jzufpzb93-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:jzufpzb93-go
