apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jzufpzb93-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jzufpzb93-go 
  name: jzufpzb93-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jzufpzb93-go 
